document.getElementById("year").textContent=new Date().getFullYear();
document.body.classList.add("motion-enabled");
const liveStates=["INGESTING EVENTS","VALIDATING SCHEMA","PROCESSING MICRO-BATCH","WRITING DELTA TABLES","SERVING DATA PRODUCTS"];
let liveIndex=0;
setInterval(()=>{const state=document.getElementById("live-state");if(state){liveIndex=(liveIndex+1)%liveStates.length;state.textContent=liveStates[liveIndex]}},1800);
const projects={
 stream:{label:"STREAMING DATA PLATFORM",title:"Weblog Stream",text:"I built this project to show how I approach a streaming pipeline from end to end. Kafka receives the events, Spark processes them with checkpoints, and Delta Lake stores the results while keeping the setup reproducible with Docker.",flow:[{step:"SOURCE",name:"Web events",detail:"JSON events"},{step:"INGEST",name:"Kafka",detail:"Durable stream"},{step:"PROCESS",name:"Spark",detail:"Checkpointed jobs"},{step:"STORE",name:"Delta Lake",detail:"Reliable tables"}],signals:["Schema evolution","Checkpoint recovery","Reproducible Docker stack"],tags:["Kafka","PySpark","Delta Lake","Docker"],url:"https://github.com/Bhanu047/weblog-stream"},
 taxi:{label:"BATCH LAKEHOUSE",title:"NYC Taxi Lakehouse",text:"This pipeline loads public taxi data, checks its quality and writes partitioned analytical tables. I designed reruns to be safe, so a failed or repeated load does not create duplicate records.",flow:[{step:"SOURCE",name:"NYC TLC",detail:"Public trip data"},{step:"VALIDATE",name:"Quality checks",detail:"Schema + rules"},{step:"MODEL",name:"DuckDB",detail:"SQL transforms"},{step:"SERVE",name:"Analytics",detail:"Repeatable reports"}],signals:["Idempotent reloads","Automated quality checks","Partitioned Parquet storage"],tags:["Python","DuckDB","Parquet","Testing"],url:"https://github.com/Bhanu047/nyc-taxi-lakehouse"},
 retail:{label:"ANALYTICS WAREHOUSE",title:"Retail Warehouse",text:"I used this project to model raw retail data into clear fact and dimension tables. The goal is consistent reporting, testable transformations and SQL models that another engineer can follow.",flow:[{step:"SOURCE",name:"Retail data",detail:"Orders + products"},{step:"STAGE",name:"dbt staging",detail:"Cleaned models"},{step:"MODEL",name:"Star schema",detail:"Facts + dimensions"},{step:"SERVE",name:"BI layer",detail:"Consistent metrics"}],signals:["Tested transformations","Fact and dimension models","Documented reporting logic"],tags:["SQL","dbt","Dimensional Modeling","Data Quality"],url:"https://github.com/Bhanu047/retail-warehouse"},
 infra:{label:"CLOUD FOUNDATION",title:"Data Platform Terraform",text:"This project packages common AWS data infrastructure into reusable Terraform modules. It demonstrates how I keep environments consistent, reviewable and ready for automated validation.",flow:[{step:"DEFINE",name:"Terraform",detail:"Reusable modules"},{step:"CHECK",name:"Plan",detail:"Validate changes"},{step:"PROVISION",name:"AWS",detail:"Cloud resources"},{step:"OPERATE",name:"Platform",detail:"Consistent setup"}],signals:["Reusable infrastructure","Plan-time validation","Environment consistency"],tags:["Terraform","AWS","IaC","CI/CD"],url:"https://github.com/Bhanu047/data-platform-terraform"}
};
const detail=document.getElementById("project-detail");
function render(key){const p=projects[key];const workflow=p.flow.map((stage,index)=>`${index?'<div class="flow-link"><i></i></div>':''}<div class="flow-stage"><small>${String(index+1).padStart(2,'0')} · ${stage.step}</small><b>${stage.name}</b><em>${stage.detail}</em></div>`).join('');detail.innerHTML=`<span class="label">${p.label}</span><h3>${p.title}</h3><p>${p.text}</p><div class="workflow-label"><span>ARCHITECTURE FLOW</span><b><i></i> LIVE</b></div><div class="architecture-flow">${workflow}</div><div class="project-signals">${p.signals.map(x=>`<span><i>✓</i>${x}</span>`).join("")}</div><div class="project-footer"><div class="tags">${p.tags.map(x=>`<span>${x}</span>`).join("")}</div><a href="${p.url}" target="_blank" rel="noreferrer">View code on GitHub ↗</a></div>`;}
document.querySelectorAll(".project-list button").forEach(btn=>btn.addEventListener("click",()=>{document.querySelectorAll(".project-list button").forEach(x=>x.classList.remove("active"));btn.classList.add("active");render(btn.dataset.project)}));render("stream");
if(!matchMedia("(prefers-reduced-motion: reduce)").matches){const els=document.querySelectorAll(".section-title,.career article,.stack-group");const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.animate([{opacity:0,transform:"translateY(18px)"},{opacity:1,transform:"none"}],{duration:550,easing:"ease",fill:"both"});observer.unobserve(e.target)}}),{threshold:.15});els.forEach(x=>observer.observe(x));}
